spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crud.cv79y9xk6zna.ap-northeast-2.rds.amazonaws.com:3306/CRUD
    username: CRUD
    password: CRUD1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # hibernate 로그 남길지

logging:
  level:
    org.hibernate.SQL: OFF
#    org.hibernate.SQL: DEBUG
#    org.hibernate.SQL: TRACE
